version: '3.8'
services:
  app:
    build: ./docker
    volumes:
      - ./app:/var/www/app
  nginx:
    image: nginx 
    ports:
      - 8090:80 
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: passwordRoot
      MYSQL_DATABASE: todo
      MYSQL_USER: Arai
      MYSQL_PASSWORD: passwordArai
    ports:
      - 3310:3306